# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'


target 'SeatGeekApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.4'
  pod 'Kingfisher', '~> 7.0'
  pod 'SwiftSpinner'


  # Pods for SeatGeekApp

  target 'SeatGeekAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SeatGeekAppUITests' do
    # Pods for testing
  end

end
